### ISSUE TITLE
Getting dependency issue

### ISSUE THREAD

**Issue by AashishChughHome** [Junyangz/upgrade-openssh-centos#1]
Hi Dear,

i am getting dependency issue after executing last command which is 

rpmbuild -ba openssh.spec

Could you please tell me where i am wrong , i am using centos 7.

Error - 
error: Failed build dependencies:                                                                                                              openssl-devel < 1.1 is needed by openssh-7.7p1-1.el7.x86_64

**Comment by Junyangz** [comment]
Comment it will work fine. Sorry for the delay in responding
