### ISSUE TITLE
升级openssh

### ISSUE THREAD

**Issue by xueanguo** [Junyangz/upgrade-openssh-centos#3]
你提供的脚本是编译升级openssh的rpms，编译之后可以在其他的centos机器直接运行吗，还是说我在centos7.4编译rpms 只能在centos7.4升级openssh，还有不支持centos6.5编译openssh，那在centos6.5升级openssh可以用这个脚本吗

**Comment by Junyangz** [comment]
都是支持的，你可以在centos7下编译打成rpm包，之后可以在其他的centos7上直接升级。同理centos6也是可以的，最终的rpm包是分el6和el7的，对应升级即可。
